In [2]:
import numpy as np
import math
#init the function with Square Matrix 4x4
squareMatrixSize=4
#Q1-i
#define the function which checks matrix is diagonally dominant or not
def checkIfDiagonallyDominant(matrix):
    #print the Matrix
    #print(matrix)
    for i in range(squareMatrixSize):
        diagonal=abs(matrix[i][i])
        sum=0
        for j in range(squareMatrixSize):
            if i!=j:
                sum+= abs(matrix[i][j])
        if(diagonal<sum):
            return "The matrix isnt diagonally dominant"
    return "The matrix is diagonally dominant"


#Main Logic Starts here
#generate a 4x4 matrix with random numbers
random_matrix_array=np.random.randint(-10,10,size=(squareMatrixSize,squareMatrixSize))
print(random_matrix_array)
print(checkIfDiagonallyDominant(random_matrix_array))


[[ 0 -2  3 -6]
 [ 7  0  2 -1]
 [-8  8 -2 -9]
 [ 6  1 -3  4]]
The matrix isnt diagonally dominant
