In [3]:
import numpy as np
import math
#init the function with Square Matrix 4x4
squareMatrixSize=4

#Common function used by upcoming Questions
#define the function to find the convergence of the given matrix
def findNorms(matrixCap):
    #init the norms    
    infiniteNorm=0.0
    frobeniusNorm=0.0
    firstNorm=0.0
    for i in range(squareMatrixSize):
        rowSum=0.0
        diagonal=matrixCap[i][i]
        for j in range(squareMatrixSize):
            absoluteValue=abs(matrixCap[i][j])
            rowSum+=absoluteValue
            frobeniusNorm+=(absoluteValue*absoluteValue)
        infiniteNorm=max(infiniteNorm,rowSum)
    frobeniusNorm=math.sqrt(frobeniusNorm)
        
    for i in range(squareMatrixSize):
        colSum=0.0
        for j in range(squareMatrixSize):
            absoluteValue=abs(matrixCap[j][i])
            colSum+=absoluteValue
        firstNorm=max(firstNorm,colSum)
        
    return "infiniteNorm:"+str(infiniteNorm)+",frobeniusNorm:"+str(frobeniusNorm)+",firstNorm:"+str(firstNorm)
        
#define function which will genenrate the cap matrix
def generateMatrixCap(matrix):
    matrixCap = matrix.astype(float)
    for i in range(squareMatrixSize):
        diagonal=matrixCap[i][i]
        if(0==diagonal):
            return -1
        for j in range(squareMatrixSize):
            matrixCap[i][j]=(matrixCap[i][j]/diagonal)
    
    return matrixCap

#define function which will genenrate the Convergence matrix Gauss Jacobi -L-U
def generateConvergencegj(matrix):
    for i in range(squareMatrixSize):
        for j in range(squareMatrixSize):
            if i==j:
                matrix[i][j]=0.0
            else:
                matrix[i][j]=-matrix[i][j]
    
    return matrix
   
#define function whihc will do Gauss Jacobi Iteration for a given square matrix  
def gjFunction(matrix):
    #print the Matrix
    print("GIVEN MATRIX:")
    print(matrix)
    print()
    
    #get the cap matrix with leading diagonal to be 1
    capMatrix=generateMatrixCap(matrix)
    if(isinstance(capMatrix,int) and capMatrix==-1):
        print("GAUSS JACOBI DOESNT CONVERGE, LEADING DIAGONAL ELEMENT IS ZERO")
        print()
        return
    print("CAP MATRIX:")
    print(capMatrix)
    print()
    
    #generate the Convergence Matrix
    convergence=generateConvergencegj(capMatrix)
    print("CONVERGENCE MATRIX OF GAUSS JACOBI:-L-U:")
    print(convergence)
    print()
    
    #get the Norms of the ConvergenceMatrix
    norms=findNorms(convergence)
    print("NORMS")
    print(norms)
    print()
    
    
#Main Logic Starts here
#generate a 4x4 matrix with random numbers
random_matrix_array=np.random.randint(-10,10,size=(squareMatrixSize,squareMatrixSize))
#pass the matrix to the function to check if it is diagonally dominant or not
print("########################################################")
gjFunction(random_matrix_array)

########################################################
GIVEN MATRIX:
[[ 1  0  1  6]
 [-9  8 -1  6]
 [ 1  2  3  5]
 [-4 -6  6  1]]

CAP MATRIX:
[[ 1.          0.          1.          6.        ]
 [-1.125       1.         -0.125       0.75      ]
 [ 0.33333333  0.66666667  1.          1.66666667]
 [-4.         -6.          6.          1.        ]]

CONVERGENCE MATRIX OF GAUSS JACOBI:-L-U:
[[ 0.         -0.         -1.         -6.        ]
 [ 1.125       0.          0.125      -0.75      ]
 [-0.33333333 -0.66666667  0.         -1.66666667]
 [ 4.          6.         -6.          0.        ]]

NORMS
infiniteNorm:16.0,frobeniusNorm:11.409517226128955,firstNorm:8.416666666666666

