In [3]:
import numpy as np
import math
#init the function with Square Matrix 4x4
squareMatrixSize=4

#Common function used by upcoming Questions
#define the function to find the convergence of the given matrix
def findNorms(matrixCap):
    #init the norms    
    infiniteNorm=0.0
    frobeniusNorm=0.0
    firstNorm=0.0
    for i in range(squareMatrixSize):
        rowSum=0.0
        diagonal=matrixCap[i][i]
        for j in range(squareMatrixSize):
            absoluteValue=abs(matrixCap[i][j])
            rowSum+=absoluteValue
            frobeniusNorm+=(absoluteValue*absoluteValue)
        infiniteNorm=max(infiniteNorm,rowSum)
    frobeniusNorm=math.sqrt(frobeniusNorm)
        
    for i in range(squareMatrixSize):
        colSum=0.0
        for j in range(squareMatrixSize):
            absoluteValue=abs(matrixCap[j][i])
            colSum+=absoluteValue
        firstNorm=max(firstNorm,colSum)
        
    return "infiniteNorm:"+str(infiniteNorm)+",frobeniusNorm:"+str(frobeniusNorm)+",firstNorm:"+str(firstNorm)
        
#define function which will genenrate the cap matrix
def generateMatrixCap(matrix):
    matrixCap = matrix.astype(float)
    for i in range(squareMatrixSize):
        diagonal=matrixCap[i][i]
        if(0==diagonal):
            return -1
        for j in range(squareMatrixSize):
            matrixCap[i][j]=(matrixCap[i][j]/diagonal)
    
    return matrixCap

#define function which will genenrate the Convergence matrix of Gauss Seidel
def generateConvergencegs(matrix):
    shape = (squareMatrixSize,squareMatrixSize)
    L=np.zeros(shape)
    I=np.identity(squareMatrixSize)
    U=np.zeros(shape)
    for i in range(squareMatrixSize):
        for j in range(squareMatrixSize):
            if i>j:
                L[i][j]=matrix[i][j]
            elif i<j:
                U[i][j]=matrix[i][j]
    #np.linalg.inv calculates invere of the given matrix
    #np.matmul multplies two matrix
    #np.negative takes one matrix as argument and output its negative
    matrix= np.negative(np.matmul(np.linalg.inv(I+L),U))
    return matrix    
    
    
#define function whihc will do Gauss Seidel Iteration for a given square matrix  -(I+L)^-1 U
def gsFunction(matrix):
    #print the Matrix
    print("GIVEN MATRIX:")
    print(matrix)
    print()
    
    #get the cap matrix with leading diagonal to be 1
    capMatrix=generateMatrixCap(matrix)
    if(isinstance(capMatrix,int) and capMatrix==-1):
        print("GAUSS SEIDEL DOESNT CONVERGE, LEADING DIAGONAL ELEMENT IS ZERO")
        print()
        return False
    print("CAP MATRIX:")
    print(capMatrix)
    print()
    
    #generate the Convergence Matrix 
    convergence=generateConvergencegs(capMatrix)
    print("CONVERGENCE MATRIX OF GAUSS SEIDEL:-(I+L)^-1  U:")
    print(convergence)
    print()
    
    #get the Norms of the ConvergenceMatrix
    norms=findNorms(convergence)
    print("NORMS")
    print(norms)
    print()
    
    
#Main Logic Starts here
#generate a 4x4 matrix with random numbers
random_matrix_array=np.random.randint(-10,10,size=(squareMatrixSize,squareMatrixSize))
#pass the matrix to the function to check if it is diagonally dominant or not
print("########################################################")
gsFunction(random_matrix_array)


########################################################
GIVEN MATRIX:
[[ 7  1 -9  3]
 [-8  1  7  0]
 [-8 -8 -4  8]
 [ 0 -3  5  7]]

CAP MATRIX:
[[ 1.          0.14285714 -1.28571429  0.42857143]
 [-8.          1.          7.          0.        ]
 [ 2.          2.          1.         -2.        ]
 [ 0.         -0.42857143  0.71428571  1.        ]]

CONVERGENCE MATRIX OF GAUSS SEIDEL:-(I+L)^-1  U:
[[-0.         -0.14285714  1.28571429 -0.42857143]
 [-0.         -1.14285714  3.28571429 -3.42857143]
 [-0.          2.57142857 -9.14285714  9.71428571]
 [-0.         -2.32653061  7.93877551 -8.40816327]]

NORMS
infiniteNorm:21.428571428571438,frobeniusNorm:18.69277467560358,firstNorm:21.9795918367347

